---
abstract: 'No-fuss instantiation of Moose objects using a single argument.'
author:
  - 'Aran Deltac <bluefeet@gmail.com>'
build_requires:
  Test::Simple: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-SingleArg
requires:
  Moose: 2.0000
resources:
  bugtracker: https://github.com/bluefeet/MooseX-SingleArg/issues
  repository: git://github.com/bluefeet/MooseX--SingleArg.git
version: 0.01
